services:
  db:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: instacopy_app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      # --- ここを追加 ---
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "827579251547-gd6qsu1k4tegalhi9c2dp60i6536nat9.apps.googleusercontent.com"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "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"
      # Nginx(web)経由の認証を正しく動作させるための設定
      SERVER_FORWARD_HEADERS_STRATEGY: native

  web:
    image: nginx:latest
    container_name: instacopy_web
    ports:
      - "9080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app