spring.application.name=instacopy
server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# グーグル認証
# グーグル認証 (環境変数から読み込むように変更)
spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# これも追加しておくと、リダイレクトの問題を防げます
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google